theme: jekyll-theme-architect
title: Welcome to Ryan G's homepage!
description: A portfolio of my data science projects and space to show some of my work to everyone! "It ain't no fun if the homies can't have none."
