theme: jekyll-theme-architect
title: Welcome to Ryan G's homepage!
description: A portfolio of my data projects and space to show some of my work to everyone! 
"Share your ideas with other people and make something NEW"
